### ISSUE TITLE
This repo mislead honest developers

### ISSUE THREAD

**Issue by ZephyrVentum** [DeligenceTechnologies/pubsub-flutter#1]
Hi, thanks a lot for your work.
However, I faced with choice between your pubnub_flutter and https://pub.dev/packages/flutter_pubnub this one. As you see second is more powerful, and currently supporter by authors. Could you remove your package or make redirect link to https://pub.dev/packages/flutter_pubnub package. It can be useful for whole flutter community to avoid misunderstanding in packages.

**Comment by deligence** [comment]
Thanks for your message. We are developing this package for our internal project. We'll study the other package and if we'll find the other package useful for our requirement, we'll also switch to that and will close our plugin.

Thanks for bringing this to my knowledge.

**Comment by deligence** [comment]
Hi @ZephyrVentum - I have marked the package Discontinued. There is no way to delete the Package and deleting the package will make the app stop working who are using the package.

Here on GitHub - I have provided the link to the other Package. Thanks once again to bring this to my knowledge.

**Comment by ZephyrVentum** [comment]
Thank you a lot!
